### PR TITLE
Add styling to the layout

### PR DESCRIPTION
**Pull request by mandelatuks**
### in this final milestone I did the following:

- Add styling to the page 
- Add a background image 
- keep the general layout according to the instruction

### CODE REVIEW

**Review by medaminedev66 — CHANGES_REQUESTED** [review]
Hi @mandelatuks  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your styling looks great.
- The repo looks professional ✔️
- Git/GitHub flow best practices have been followed ✔️
- There are no linter errors ✔️

## Required Changes ♻️
- [ ] Your README screenshot does not represent the project "LeaderBoard". It would be better to remove it or replace it with a screenshot of your current project.
- [ ] The live link leads to the wrong page. I recommend fixing that so your project is documented professionally.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mandelatuks** [comment]
@medaminedev66 
kindly check its development branch everything the image is in the development branch once I merge it the it will be seen to the main well

**Comment by mandelatuks** [comment]
@medaminedev66 
kindly check its development branch everything in the image is in the development branch once I merge it it will be seen to the main well

**Review by prolajumokeoni — APPROVED** [review]
Hi @mandelatuks, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Always add changes to the branch on which you are requesting review, so that the reviewer can approve if the pull request passes all the requirement 👍🏿 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
